tls:
  options:
    default:
      # set the minimum TLS version to TLS 1.2 for high security, with some back-compatibility
      # note this will prevent some very old and insecure systems from connecting
      minVersion: VersionTLS12
      # restrict to secure cipher suites since TLS 1.2 is on
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
http:
  middlewares:
    # define a middleware that permanently redirects all requests to the https equivalent
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    # middleware that appends a basic HSTS security header
    hsts:
      headers:
        stsSeconds: 63072000
    # middleware that appends a full domain-wide, preloaded HSTS header
    # read docs about HSTS preload, and its implications, before using this middleware
    # https://hstspreload.org/#deployment-recommendations
    hsts-preload:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
    # redirect .well/known/carddav and ./well-known/caldav to the correct Nextcloud URL
    # this is necessary as Nextcloud does not serve this redirect correctly behind a backproxy
    # this is based on a recommendation from the official Nextcloud docs for Service Discovery
    # https://docs.nextcloud.com/server/21/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=traefik#traefik-2
    nextcloud-dav-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"
